projects:
  - name: A1
    queues_default:
      notify_base: "http://localhost:8080"
      notify_timeout: 5
      retry_times: 40
      retry_duration: 300
      binding_exchange: fishtrip
    queues:
      - queue_name: "q1"
        notify_path: "/test.html"
        routing_key:
          - "order.state.paid"
      - queue_name: "q2"
        notify_path: "/test.html"
        routing_key:
          - "order.state.*"

  - name: A2
    queues_default:
      notify_base: "http://localhost:8080"
      notify_timeout: 5
      retry_times: 40
      retry_duration: 300
      binding_exchange: fishtrip
    queues:
      - queue_name: "q3"
        notify_path: "/test.html"
        routing_key:
          - "order.state.paid"
      - queue_name: "q4"
        notify_path: "/test.html"
        routing_key:
          - "order.state.*"
###test
  - name: A2
    queues_default:
      notify_base: "http://localhost:8080"
      notify_timeout: 5
      retry_times: 40
      retry_duration: 300
      binding_exchange: fishtrip
    queues:
      - queue_name: "q3"
        notify_path: "/test.html"
        routing_key:
          - "order.state.paid"
      - queue_name: "q4"
        notify_path: "/test.html"
        routing_key:
          - "order.state.*"